SIEG/Controllers/MemberController.cs
using Microsoft.AspNetCore.Mvc;
using SIEG.Models;
using System.Diagnostics;

namespace SIEG.Controllers
{
    public class MemberController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Member_buyerorder()
        {
            return View();
        }

        public IActionResult Member_personal()
        {
            return View();
        }

        public IActionResult Member_Membermodification()
        {
            return View();
        }

        public IActionResult Member_coupon()
        {
            return View();
        }

        public IActionResult Member_ProductCollection()
        {
            return View();
        }
        public IActionResult SellerAddProduct()
        {
            return View();
        }

        public IActionResult FavoritePosts()
        {
            return View();
        }

        public IActionResult SettingCreditcard()
        {
            return View();
        }

        public IActionResult PaymentInformation()
        {
            return View();
        }

        public IActionResult Mailinginformation()
        {
            return View();
        }

        public IActionResult Sellerinformation()
        {
            return View();
        }
        public IActionResult Passwordmodification()
        {
            return View();
        }

        public IActionResult Kyccertified()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        [HttpPost("FileUploads")]
        public async Task<IActionResult> Index2(List<IFormFile> image_uploads)
        {
            long size = image_uploads.Sum(f => f.Length);

            var filePaths = new List<string>();
            foreach (var formFile in image_uploads)
            {
                if (formFile.Length > 0)
                {
                    //臨時位置文件的完整路徑
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/Benicon/memberidcard", formFile.FileName);
                    filePaths.Add(filePath);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                    }
                }
            }
            //處理上傳的文件
            //不要依賴或信任未經驗證的 FileName 屬性。
            //return Ok(new { count = image_uploads.Count, size, filePaths });
            //await Task.Delay(2900);
            return View("~/Views/Member/Kyccertified.cshtml");
        }
    }
}

SIEG/Controllers/aboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace SIEG.Controllers
{
    public class aboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SIEG/Controllers/contactController.cs
using Microsoft.AspNetCore.Mvc;

namespace SIEG.Controllers
{
    public class contactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SIEG/Controllers/news_listController.cs
using Microsoft.AspNetCore.Mvc;

namespace SIEG.Controllers
{
    public class news_listController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SIEG/Views/Shared/_FooterPartial.cshtml
<!-- Footer -->
<div class="footer">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-3">
                <div class="footer_logo">
                    <a href="index.html">
                        <img src="~/images/logo-white.png" alt="">
                    </a>
                </div>
            </div>
            <div class="col-lg-9 d-block align-items-center justify-content-between d-lg-flex">
                <ul class="footer_menu">
                    <li><a asp-controller="about" asp-action="index">關於我們</a></li>
                    <li><a asp-controller="news_list" asp-action="index">最新消息</a></li>
                    <li><a asp-controller="product_list" asp-action="index">商品介紹</a></li>
                    <li><a asp-controller="forum_list" asp-action="index">討論專區</a></li>
                    <li><a asp-controller="contact" asp-action="index">聯絡我們</a></li>
                    <li><a onclick="memberLogin()">會員中心</a></li>
                </ul>
                <ul class="footer_social">
                    <li class="fb"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                    <li class="ins"><a href="#"><i class="fab fa-instagram"></i></a></li>
                    <li class="twitter"><a href="#"><i class="fab fa-twitter"></i></a></li>
                </ul>
            </div>
            <div class="col-12">
                <div class="copyright">
                    <div>Copyright © 2022 - All Right Reserved. ∣ <a asp-controller ="disclaimer" asp-action="index">免責聲明</a></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function memberLogin(){
        mID = sessionStorage.getItem("mID");
        console.log(mID);
        if (mID == "" || mID == null) {
            window.location = "/D_Personal";
        }
        else {
            window.location = "/Member/Member_buyerorder";
        }
    }
</script>

SIEG/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh-Hant-TW">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - S.I.E.G</title>

    <!-- Google Web Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@700&family=Open+Sans:wght@400;500;600&display=swap"
          rel="stylesheet">
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <!-- Libraries Stylesheet -->
    <link href="~/lib/animate/animate.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet" asp-append-version="true" />
    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/responsive.css" rel="stylesheet" asp-append-version="true" />

    <style>
        .member_login.div_hide{
            display:none !important;
        }

        .member_login.div_show {
            display: block !important;
        }
    </style>

    @await RenderSectionAsync("Style", required: false)

</head>
<body>

    <!-- header -->
    <div class="header_sec sticky-top" id="headerVue">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-5">
                    <a class="d-flex align-items-center header_logo" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/logo.png" alt="logo-image" class="img-fluid">
                    </a>
                </div>
                <div class="col-md-9 col-7 d-flex align-items-center justify-content-end">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar"
                             aria-labelledby="offcanvasNavbarLabel">
                            <div class="offcanvas-header">
                                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                                        aria-label="Close"></button>
                            </div>
                            <div class="offcanvas-body">
                                <div class="navbar-nav ms-auto">
                                    <a class="nav-item nav-link" asp-controller="about" asp-action="index">關於我們</a>
                                    <div class="nav-item dropdown">
                                        <a class="nav-link" asp-controller="news_list" asp-action="index">最新消息</a>
                                        <i class="bi bi-chevron-down dropdown-toggle" data-bs-toggle="dropdown"></i>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" v-for="item in NewsSortDTO" @@click="newsSortToList(item.newssortName)">{{item.newssortName}}</a>
                                        </div>
                                    </div>
                                    <div class="nav-item dropdown">
                                        <a class="nav-link" asp-controller="product_list" asp-action="index">商品介紹</a>
                                        <i class="bi bi-chevron-down dropdown-toggle" data-bs-toggle="dropdown"></i>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" v-for="item in ProductSortDTO" @@click="ProductSortToList(item.productsortName)">{{item.productsortName}}</a>
                                        </div>
                                    </div>
                                    <div class="nav-item dropdown">
                                        <a class="nav-link" asp-controller="forum_list" asp-action="index">討論專區</a>
                                        <i class="bi bi-chevron-down dropdown-toggle" data-bs-toggle="dropdown"></i>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" v-for="item in ProductSortDTO" @@click="ForumSortToList(item.productsortName)">{{item.productsortName}}</a>
                                        </div>
                                    </div>
                                    <a class="nav-item nav-link" asp-controller="contact" asp-action="index">聯絡我們</a>
                                    <div class="nav-item dropdown d-block d-lg-none member_login">
                                        <a asp-controller="Member" asp-action="Kyccertified" class="nav-link">會員中心</a>
                                        <i class="bi bi-chevron-down dropdown-toggle" data-bs-toggle="dropdown"></i>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" asp-controller="Member" asp-action="Kyccertified">KYC權限認證</a>
                                            <a class="dropdown-item" asp-controller="Member" asp-action="Member_buyerorder">購買</a>
                                            <a class="dropdown-item" asp-controller="Member" asp-action="SellerAddProduct">出售</a>
                                            <a class="dropdown-item" asp-controller="Member" asp-action="Member_personal">個人資料</a>
                                            <a class="dropdown-item" asp-controller="Member" asp-action="Member_coupon">優惠券</a>
                                            <a class="dropdown-item" asp-controller="Member" asp-action="Member_ProductCollection">商品收藏組合</a>
                                            <a class="dropdown-item" asp-controller="Member" asp-action="FavoritePosts">貼文收藏組合</a>
                                            <a class="dropdown-item" asp-controller="Member" asp-action="SettingCreditcard">設定</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <ul class="header_icon">
                            <li class="header_user">
                                <a @@click="memberLogin">
                                    <img src="~/images/icon-user.png" alt="img">
                                </a>
                            </li>
                            @*<li class="header_notice">
                                <a href="D_Personal">
                                    <img src="~/images/icon-notice.png" alt="img">
                                </a>
                                <span class="new_notice"></span>
                            </li>*@
                            <li class="header_search">
                                <a href="javascript:void(0)">
                                    <img src="~/images/icon-search.png" alt="img">
                                </a>
                            </li>
                        </ul>
                        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
                                aria-controls="offcanvasNavbar">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </nav>
                </div>
            </div>
        </div>
        <!-- search form -->
        <div class="header_search_form">
            <form action="ProductList">
                <button type="button" class="fa fa-search" @@click="searchProsuct"></button>
                <input type="text" name="search_content" placeholder="Search" class="searchInput">
            </form>
        </div>
    </div>


    <main role="main">
        @RenderBody()
    </main>


    @await RenderSectionAsync("footer", required: false)

    <!-- Top -->
    <a href="#" class="back-to-top"><i class="bi bi-arrow-up"></i></a>

    <!-- JavaScript Libraries -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/wow/wow.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/counterup/counterup.min.js"></script>
    <script src="~/lib/parallax/parallax.min.js"></script>
    <script src="~/lib/lightbox/js/lightbox.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue@2.7.14/dist/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.2.2/axios.min.js"></script>

    <script>
        var webApiBaseAddress = "https://localhost:7139";
        var appVue = new Vue({
            el: "#headerVue",
            name: "headerVue",
            data: {
                Filter: "",
                NewsSortDTO: [],
                newssortId: null,
                newssortName: null,
                ProductSortDTO: [],
                productsortId: null,
                productsortImg: null,
                productsortBrand: null,
                productsortSort: null,
            },
            mounted: function () {
                let _this = this;
                _this.getNewsSortDTO();
                _this.getProductSortDTO();

            },
            methods: {
                getNewsSortDTO: function () {
                    let _this = this;
                    axios.get(`${webApiBaseAddress}/api/E_NewsSort`).then(
                        response => {
                            _this.NewsSortDTO = response.data;
                            var NewsSort = [];
                            for (let i = 0; i < _this.NewsSortDTO.length; i++) {
                                let item = {};
                                item = _this.NewsSortDTO[i];
                                NewsSort.push(item);
                            }
                            _this.NewsSortDTO = NewsSort;
                        }
                    );
                },
                newsSortToList: function (sortName) {
                    sessionStorage.setItem("indexNSortName", sortName);
                    window.location = "/news_list";
                },
                getProductSortDTO: function () {
                    let _this = this;
                    axios.get(`${webApiBaseAddress}/api/E_ProductSort`).then(
                        response => {
                            _this.ProductSortDTO = response.data;
                            //console.log(response.data);
                        }
                    );
                },
                ProductSortToList: function (sortName) {
                    sessionStorage.setItem("indexPSortName", sortName);
                    window.location = "/product_list";
                },
                ForumSortToList: function (sortName) {
                    sessionStorage.setItem("indexPSortName", sortName);
                    window.location = "/forum_list";
                },
                memberLogin: function () {
                    mID = sessionStorage.getItem("mID");
                    //console.log(mID);
                    if (mID == "" || mID == null) {
                        window.location = "/D_Personal";
                    }
                    else {
                        window.location = "/Member/Kyccertified";
                    }
                },
                searchProsuct: function () {
                    sessionStorage.setItem("pKeyword", $(".searchInput").val());
                    window.location = "/product_list";
                },
            },
        });
    </script>
    <script>
        let mID = sessionStorage.getItem("mID");
        if (mID == "" || mID == null) {
            $('.member_login').hide();
            $('.member_login').addClass('div_hide');
        }
        else {
            $('.member_login').show();
            $('.member_login').addClass('div_show');
        }

    </script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

SIEG/Views/Shared/_MemberBanner.cshtml
<!-- Page Banner -->
<div class="page_banner" style="background-image: url(../images/1920x350-1.jpg)">
	<div class="container">
		<div class="content">
			<h1 class="page_title">My-Account</h1>
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item"><a href="index.html">Home</a></li>
					<li class="breadcrumb-item active">會員中心</li>
				</ol>
			</nav>
		</div>
	</div>
</div>

SIEG/Views/Shared/_Membersidebar.cshtml
<!-- Content -->
<!-- 側邊攔 -->
<div class="col-lg-3 d-lg-block d-none" style="background-color: #fafafa;">
    <div class="MemberFrame">
        <div class="namefont">
            {{PersonalDTOes.name}}
        </div>
        <a asp-area="" asp-controller="Member" asp-action="Kyccertified" class="Aelement SidebarKYC">
            <div class="MemberSidebar ">
                <div>
                    @*  <img src="~/images/benicon/padlock.png" class="AccountIcon" />*@
                    <img src="~/images/benicon/padlock.png" class="AccountIcon " />
                </div>
                <div>
                    <div class="title">
                        KYC權限認證
                    </div>
                    <div class="titlehint">
                        賣家認證
                    </div>
                </div>
            </div>
        </a>

        <a asp-area="" asp-controller="Member" asp-action="Member_buyerorder" class="Aelement SidebarBuyerOrders">
            <div class="MemberSidebar">
                <div>
                    <img src="/images/Benicon/delivery-box.png" class="AccountIcon">
                </div>
                <div>
                    <div class="title">
                        購買
                    </div>
                    <div class="titlehint">
                        有效出價、進行中、已完成訂單
                    </div>
                </div>
            </div>
        </a>


        <a asp-area="" asp-controller="Member" asp-action="SellerAddProduct" class="Aelement SidebarSellerAddProduct" v-if="PersonalDTOes.access==2">
            <div class="MemberSidebar">
                <div>
                    <img src="~/images/Benicon/money.png" class="AccountIcon">
                </div>
                <div>
                    <div class="title">
                        出售
                    </div>
                    <div class="titlehint">
                        有效出價、進行中、已完成訂單
                    </div>
                </div>
            </div>
        </a>
        <a v-else>

        </a>

        <a asp-area="" asp-controller="Member" asp-action="Member_personal" class="Aelement SidebarMember">
            <div class="MemberSidebar">
                <div>
                    <img src="~/images/Benicon/user.png" class="AccountIcon">
                </div>
                <div>
                    <div class="title">
                        個人資料
                    </div>
                    <div class="titlehint">
                        了解您的獨特之處
                    </div>
                </div>
            </div>
        </a>

        <a asp-area="" asp-controller="Member" asp-action="Member_coupon" class="Aelement SidebarCoupon">
            <div class="MemberSidebar">
                <div>
                    <img src="~/images/Benicon/Coupon.png" class="AccountIcon">
                </div>
                <div>
                    <div class="title">
                        優惠卷
                    </div>
                    <div class="titlehint">
                        查詢優惠卷剩餘數量
                    </div>
                </div>
            </div>
        </a>

        @*<a href="notice.html" class="Aelement">
        <div class="MemberSidebar">
        <div>
        <img src="~/images/Benicon/notification.png" class="AccountIcon">
        </div>
        <div>
        <div class="title">
        簡訊中心
        </div>
        <div class="titlehint">
        查看最新簡訊
        </div>
        </div>
        </div>
        </a>*@

        <a asp-area="" asp-controller="Member" asp-action="Member_ProductCollection" class="Aelement SidebarProductCollection">
            <div class="MemberSidebar">
                <div>
                    <img src="~/images/Benicon/heart.png" class="AccountIcon">
                </div>
                <div>
                    <div class="title">
                        商品收藏組合
                    </div>
                    <div class="titlehint">
                        查看您的商品內容
                    </div>
                </div>
            </div>
        </a>
        <a asp-area="" asp-controller="Member" asp-action="FavoritePosts" class="Aelement SidebarFavoritePosts">
            <div class="MemberSidebar">
                <div>
                    <img src="~/images/benicon/portfolio.png" class="AccountIcon">
                </div>
                <div>
                    <div class="title">
                        貼文收藏組合
                    </div>
                    <div class="titlehint">
                        查看您的貼文內容
                    </div>
                </div>
            </div>
        </a>


        <a asp-area="" asp-controller="Member" asp-action="SettingCreditcard" class="Aelement SidebarSetting">
            <div class="MemberSidebar">
                <div>
                    <img src="~/images/Benicon/settings.png" class="AccountIcon">
                </div>
                <div>
                    <div class="title">
                        設定
                    </div>
                    <div class="titlehint">
                        預設付款、收款、地址
                    </div>
                </div>
            </div>
        </a>

        <a  class="Aelement" onclick='Signout()'>
            <div class="MemberSidebar">
                <div>
                    <img src="~/images/Benicon/exit.png" class="AccountIcon">
                </div>
                <div>
                    <div class="title">
                        登出
                    </div>
                </div>
            </div>
        </a>
    </div>
</div>
<script>
    function Signout() {
        sessionStorage.removeItem("mID");
        localStorage.removeItem("GETmID");
        window.location = "/D_Personal"
    }
</script>

SIEG/Views/Shared/_NoDataPartial.cshtml
<!-- No Data -->
<div class="no_data">
    <img src="images/icon-info.png">
    <div>目前尚無資訊</div>
</div>